FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# The --host flag is required to access Vite from your browser when in Docker
CMD ["npm", "run", "dev", "--", "--host"]